name: First Workflow
on: [push]

# 1 v több job-ot kell tartalmazzon

jobs:
  run-shell-commands: ##needs-be lehet hivatkozni
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline command
        run: |
          node -v
          npm -v

  paralell-job-macos:
    runs-on: macos-latest
    steps:
      - name: View sw version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands ##job megnevezés
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error Step
        run: doesnotexists ## ez azért kell h errort idézzünk elő
